--DROP TABLE TB_GRADE;
--DROP TABLE TB_CLASS_PROFESSOR;
--DROP TABLE TB_CLASS;
--DROP TABLE TB_STUDENT;
--DROP TABLE TB_PROFESSOR;
--DROP TABLE TB_DEPARTMENT;
-----------------------------------------------------------------------------------------------------
CREATE TABLE TB_DEPARTMENT(
    DEPARTMENT_NO VARCHAR2(10) CONSTRAINT TB_DEPARTMENT_NO_NN NOT NULL, 
    DEPARTMENT_NAME VARCHAR2(40) CONSTRAINT TB_DEPARTMENT_NAME_NN NOT NULL,
    CATEGORY VARCHAR2(40), 
    OPEN_YN CHAR(1),
    CAPACITY NUMBER,
    CONSTRAINT TB_DEPARTMENT_NO_PK PRIMARY KEY(DEPARTMENT_NO)
);

COMMENT ON COLUMN TB_DEPARTMENT.DEPARTMENT_NO IS '학과 번호';
COMMENT ON COLUMN TB_DEPARTMENT.DEPARTMENT_NAME IS '학과 이름';
COMMENT ON COLUMN TB_DEPARTMENT.CATEGORY IS '계열';
COMMENT ON COLUMN TB_DEPARTMENT.OPEN_YN IS '개설 여부';
COMMENT ON COLUMN TB_DEPARTMENT.CAPACITY IS '정원';

-- 확인용
--SELECT * FROM TB_DEPARTMENT;
-- 삭제용
--DROP TABLE TB_DEPARTMENT;
------------------------------------------------------------------------------------------------
CREATE TABLE TB_PROFESSOR(
    PROFESSOR_NO VARCHAR2(10) CONSTRAINT TB_PROFESSOR_NO_NN NOT NULL,
    PROFESSOR_NAME VARCHAR2(40) CONSTRAINT TB_PROFESSOR_NAME_NN NOT NULL,
    PROFESSOR_SSN VARCHAR2(14),
    PROFESSOR_ADDRESS VARCHAR(200), 
    DEPARTMENT_NO VARCHAR2(20) CONSTRAINT TB_PROFESSOR_DENO_FK REFERENCES TB_DEPARTMENT(DEPARTMENT_NO),
    CONSTRAINT TB_PROFESSOR_NO_PK PRIMARY KEY(PROFESSOR_NO)
);

COMMENT ON COLUMN TB_PROFESSOR.PROFESSOR_NO IS '교수 번호';
COMMENT ON COLUMN TB_PROFESSOR.PROFESSOR_NAME IS '교수 이름';
COMMENT ON COLUMN TB_PROFESSOR.PROFESSOR_SSN IS '교수 주민번호';
COMMENT ON COLUMN TB_PROFESSOR.PROFESSOR_ADDRESS IS '교수 주소';
COMMENT ON COLUMN TB_PROFESSOR.DEPARTMENT_NO IS '학과 번호';


-- 확인용
--SELECT * FROM TB_PROFESSOR;
-- 삭제용
--DROP TABLE TB_PROFESSOR;

------------------------------------------------------------------------------------------------
CREATE TABLE TB_STUDENT(
    STUDENT_NO VARCHAR2(10) CONSTRAINT TB_STUDENT_ST_NO_NN NOT NULL,
    DEPARTMENT_NO VARCHAR2(10) CONSTRAINT TB_STUDENT_DE_NO_NN NOT NULL,
    STUDENT_NAME VARCHAR2(40) CONSTRAINT TB_STUDENT_ST_NAME_NN NOT NULL,
    STUDENT_SSN VARCHAR2(14),
    STUDENT_ADDRESS VARCHAR2(200),
    ENTRANCE_DATE DATE,
    ABSENCE_YN CHAR(1), 
    COACH_PROFESSOR_NO VARCHAR2(20) CONSTRAINT TB_STUDENT_PROFESSOR_FK REFERENCES TB_PROFESSOR,
    CONSTRAINT TB_STUDENT_ST_NO_PK PRIMARY KEY(STUDENT_NO),
    CONSTRAINT TB_STUDENT_DE_NO_FK FOREIGN KEY(DEPARTMENT_NO) REFERENCES TB_DEPARTMENT(DEPARTMENT_NO)
);

COMMENT ON COLUMN TB_STUDENT.STUDENT_NO IS '학생 번호';
COMMENT ON COLUMN TB_STUDENT.DEPARTMENT_NO IS '학과 번호';
COMMENT ON COLUMN TB_STUDENT.STUDENT_NAME IS '학생 이름';
COMMENT ON COLUMN TB_STUDENT.STUDENT_SSN IS '학생 주민번호';
COMMENT ON COLUMN TB_STUDENT.STUDENT_ADDRESS IS '학생 주소';
COMMENT ON COLUMN TB_STUDENT.ENTRANCE_DATE IS '입학 일자';
COMMENT ON COLUMN TB_STUDENT.ABSENCE_YN IS '휴학 여부';
COMMENT ON COLUMN TB_STUDENT.COACH_PROFESSOR_NO IS '지도 교수 번호';

--SELECT * FROM TB_STUDENT;
--DROP TABLE TB_STUDENT;
------------------------------------------------------------------------------------------------
CREATE TABLE TB_CLASS(
    CLASS_NO VARCHAR2(10) CONSTRAINT TB_CLASS_NO_NN NOT NULL,
    DEPARTMENT_NO VARCHAR2(20) CONSTRAINT TB_CLASS_DENO_NN NOT NULL,
    PREATTENDING_CLASS_NO VARCHAR2(20), 
    CLASS_NAME VARCHAR2(60) CONSTRAINT TB_CLASS_NAME_NN NOT NULL, 
    CLASS_TYPE VARCHAR2(20), 
    CONSTRAINT TB_CLASS_NO_PK PRIMARY KEY(CLASS_NO),
    CONSTRAINT TB_CLASS_DE_NO_FK FOREIGN KEY(DEPARTMENT_NO) REFERENCES TB_DEPARTMENT(DEPARTMENT_NO)
);

ALTER TABLE TB_CLASS ADD CONSTRAINT TB_CLASS_PREATTEND_FK 
    FOREIGN KEY(PREATTENDING_CLASS_NO) REFERENCES TB_CLASS(CLASS_NO);
--ALTER TABLE 테이블명 MODIFY 컬럼명 변경할 데이터타입
 ALTER TABLE TB_CLASS MODIFY CLASS_TYPE VARCHAR2(15);  
    
    
COMMENT ON COLUMN TB_CLASS.CLASS_NO IS '과목 번호';
COMMENT ON COLUMN TB_CLASS.DEPARTMENT_NO IS '학과 번호';
COMMENT ON COLUMN TB_CLASS.PREATTENDING_CLASS_NO IS '선수 과목 번호';
COMMENT ON COLUMN TB_CLASS.CLASS_NAME IS '과목 이름';
COMMENT ON COLUMN TB_CLASS.CLASS_TYPE IS '과목 구분';

--DROP TABLE TB_CLASS;
------------------------------------------------------------------------------------------------
CREATE TABLE TB_CLASS_PROFESSOR(
    CLASS_NO VARCHAR2(10) CONSTRAINT TB_CLASS_PROF_CLNO_NN NOT NULL, 
    PROFESSOR_NO VARCHAR2(10) CONSTRAINT TB_CLASS_PROF_NO_NN NOT NULL,
    CONSTRAINT TB_CLASS_PROF_CLNO_PK PRIMARY KEY(CLASS_NO, PROFESSOR_NO),
    CONSTRAINT TB_CLASS_PROF_CLNO_FK FOREIGN KEY(CLASS_NO) REFERENCES TB_CLASS(CLASS_NO),
    CONSTRAINT TB_CLASS_PROF_NO_FK FOREIGN KEY(PROFESSOR_NO) REFERENCES TB_PROFESSOR        
);
COMMENT ON COLUMN TB_CLASS_PROFESSOR.CLASS_NO IS '과목 번호';
COMMENT ON COLUMN TB_CLASS_PROFESSOR.PROFESSOR_NO IS '교수 번호';

--DROP TABLE TB_CLASS_PROFESSOR;
------------------------------------------------------------------------------------------------
CREATE TABLE TB_GRADE(
    TERM_NO VARCHAR2(10) CONSTRAINT TB_GRADE_TERM_NO_NN NOT NULL,
    CLASS_NO VARCHAR2(10)CONSTRAINT TB_GRADE_CLASS_NO_NN NOT NULL,
    STUDENT_NO VARCHAR2(10) CONSTRAINT TB_GRADE_STUDENT_NO_NN NOT NULL,
    POINT NUMBER(3, 2), 
    CONSTRAINT TB_GRADE_TERM_NO_PK PRIMARY KEY(TERM_NO, CLASS_NO, STUDENT_NO), 
    CONSTRAINT TB_GRADE_CLASS_NO_FK FOREIGN KEY(CLASS_NO) REFERENCES TB_CLASS(CLASS_NO),
    CONSTRAINT TB_GRADE_STUDENT_NO_FK FOREIGN KEY(STUDENT_NO) REFERENCES TB_STUDENT(STUDENT_NO)
);
COMMENT ON COLUMN TB_GRADE.TERM_NO IS '학기 번호';
COMMENT ON COLUMN TB_GRADE.CLASS_NO IS '과목 번호';
COMMENT ON COLUMN TB_GRADE.STUDENT_NO IS '학생 번호';
COMMENT ON COLUMN TB_GRADE.POINT IS '학점';

--DROP TABLE TB_GRADE;
------------------------------------------------------------------------------------------------
-- INSERT INTO 테이블명[(컬럼명, ..., 컬럼명)] VALUES (값, ..., 값);
--INSERT INTO TB_DEPARTMENT(DEPARTMENT_NO, DEPARTMENT_NAME) VALUES ('452745', '경영학과');
--SELECT * FROM TB_DEPARTMENT;
--ROLLBACK;